# 容器 配置
server:
  port: 83
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/ictgu?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1614325697zyk
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5
  mail:
    host: smtp.qq.cm
    username: 1684864253@qq.com
    password: 1614325697zyk
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: 沧海云
  domain: ictgu.cn
